### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by liuslevis** [JustinFincher/WebDrop#1]
After git clone, I type:
➜  ChromeShare  pod install
[!] Invalid `Podfile` file: undefined method `inherit!' for #Pod::Podfile:0x007faadc8a8980. Updating CocoaPods might fix the issue.

In Xcode 7.3, when I clicked run:
ld: warning: directory not found for option '-L/Users/richliu/Library/Developer/Xcode/DerivedData/WebDrop-eikfrfpfulcqbqhhskoawxgmsdti/Build/Products/Debug/MASShortcut'
ld: library not found for -lMASShortcut
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liuslevis** [comment]
Open ChromeShare.xcworkspace with Xcode solve this problem.

**Comment by liuslevis** [comment]
There's still nothing happen after I run the project.
It would be greate if any setup detail is provided in README

**Comment by JustinFincher** [comment]
Hi, sorry for my late reply. ;-)
If you run the project, you will notice a new icon on the menu bar -- that is WebDrop, then you can set a global shortcut through settings.
I will provide a release in tag 1.0 and a how-to guide.

**Comment by JustinFincher** [comment]
[How-to-install](https://github.com/JustinFincher/WebDrop/wiki/How-to-install)  Here is the 1.0 release, if you found nothing on your menu bar after the run, plz mention me, thank you. ;-)

**Comment by liuslevis** [comment]
Thanks a lot.
